name: Concurrency 1
run-name: Concurrency 1 (${{ inputs.environment }})
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true
# this can be used at workflow or job level. Here is an example of workflow level
concurrency: 
  # group: concurrency-group-1
  group: ${{ github.workflow }} - ${{ github.event.inputs.environment }}
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30